language: node_js
node_js:
  - "5.1"

services:
  - postgresql

before_script:
  - psql -U postgres -c "CREATE DATABASE mangal_dev;"
  - psql -U postgres -c "CREATE EXTENSION postgis;"

install:
  - npm install

script:
  - npm test
